/**
 * Regenerates the header icon glyphs from the Figma source file, so what we ship
 * is Figma's own geometry — never hand-traced or hand-tuned.
 *
 * Input:  design-reference/figma/file-full.json (a full REST `GET /files` dump,
 *         which carries each node's exact fillGeometry / strokeGeometry).
 * Output: src/components/ui/icon-glyphs.tsx (committed, generated — do not edit).
 *
 * Figma exports a node's stroke as a *filled outline* path (strokeGeometry), so
 * we emit `<path fill=...>` — identical to Figma's own SVG export. One exception:
 * an INSIDE-aligned RECTANGLE's strokeGeometry comes back doubled in the REST
 * dump, so rectangles are redrawn from their exact size / cornerRadius / weight
 * (verified pixel-identical to Figma's render). Run: `node scripts/generate-icons.mjs`.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const doc = JSON.parse(
  fs.readFileSync(
    path.join(ROOT, "design-reference/figma/file-full.json"),
    "utf8",
  ),
).document;

// glyph name -> Figma node id (leading/header icons)
const NODES = {
  camera: "68:9780",
  shield: "68:9911",
  sensor: "68:9896",
  grid: "68:9923",
};

const find = (n, id) =>
  n.id === id ? n : (n.children || []).reduce((a, c) => a || find(c, id), null);
const num = (v) => `${(+v).toFixed(4)}`.replace(/\.?0+$/, "");
const hex = (arr) => {
  const p = (arr || []).find((x) => x.type === "SOLID" && x.visible !== false);
  if (!p) return null;
  const c = p.color;
  return (
    "#" +
    ["r", "g", "b"]
      .map((k) =>
        Math.round(c[k] * 255)
          .toString(16)
          .padStart(2, "0"),
      )
      .join("")
  );
};
const mat = (t) =>
  `matrix(${[t[0][0], t[1][0], t[0][1], t[1][1], t[0][2], t[1][2]].map(num).join(" ")})`;
const rule = (g) => (g.windingRule === "EVENODD" ? "evenodd" : "nonzero");

function self(node) {
  const fill = hex(node.fills);
  const stroke = hex(node.strokes);
  if (node.type === "RECTANGLE" && node.strokes?.length) {
    const sw = node.strokeWeight ?? 1;
    const inset = { INSIDE: sw / 2, OUTSIDE: -sw / 2 }[node.strokeAlign] || 0;
    const { x: w, y: h } = node.size;
    const cr = node.cornerRadius || 0;
    const r = `x="${num(inset)}" y="${num(inset)}" width="${num(w - 2 * inset)}" height="${num(h - 2 * inset)}" rx="${num(Math.max(cr - inset, 0))}"`;
    return (
      (fill ? `<rect ${r} fill="${fill}" />` : "") +
      `<rect ${r} fill="none" stroke="${stroke}" strokeWidth="${num(sw)}" />`
    );
  }
  let out = "";
  for (const g of node.fillGeometry || [])
    if (fill)
      out += `<path d="${g.path}" fill="${fill}" fillRule="${rule(g)}" />`;
  for (const g of node.strokeGeometry || [])
    if (stroke)
      out += `<path d="${g.path}" fill="${stroke}" fillRule="${rule(g)}" />`;
  return out;
}
const body = (node) =>
  (node.children || [])
    .map((c) => {
      const inner = self(c) + body(c);
      return inner
        ? `<g transform="${mat(c.relativeTransform)}">${inner}</g>`
        : "";
    })
    .join("");

const entries = Object.entries(NODES).map(([name, id]) => {
  const n = find(doc, id);
  const { x: w, y: h } = n.size;
  return `  ${name}: {\n    viewBox: "0 0 ${num(w)} ${num(h)}",\n    glyph: (\n      <>\n        ${body(n)}\n      </>\n    ),\n  },`;
});

const file = `// GENERATED by scripts/generate-icons.mjs from the Figma source — do not edit.
// These are Figma's own fill/stroke geometry (identical to a Figma SVG export),
// so the header glyphs are pixel-accurate to the design. Regenerate with
// \`node scripts/generate-icons.mjs\` if the Figma icons change.
import type { ReactElement } from "react";

export const HEADER_GLYPHS: Record<string, { viewBox: string; glyph: ReactElement }> = {
${entries.join("\n")}
};
`;
const outPath = path.join(ROOT, "src/components/ui/icon-glyphs.tsx");
fs.writeFileSync(outPath, file);
console.log("wrote", outPath);
